version: '3'
services:
  sreality_viewer:
    build: ./sreality_viewer
    ports:
      - "8080:8081"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Praha123
      POSTGRES_DB: sreality
    ports:
      - "5432:5432"