version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8081"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Praha123
      POSTGRES_DB: sreality
